CREATE DATABASE IF NOT EXISTS customer_behaviour;
SELECT * FROM mytable;

-- Q1.  What is the total revenue generated by male v/s female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM mytable
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount 
FROM mytable
WHERE discount_applied = "Yes" 
AND purchase_amount > 
	(SELECT AVG(purchase_amount) FROM mytable);
    
-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2)
FROM mytable
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average purchase amount between Standard and Express shipping
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) AS Average
FROM mytable
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total 
-- revenue between subscribers and non-subscribers.

SELECT subscription_status, 
COUNT(customer_id) AS total_customer,
SUM(purchase_amount) AS total_revenue, 
ROUND(AVG(purchase_amount), 2) AS average_spend
FROM mytable
GROUP BY subscription_status
ORDER BY 3, 4 DESC;


--  Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(100 * (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*)), 2) AS discount_applied
FROM mytable
GROUP BY item_purchased
ORDER BY 2 DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning and Loyal based on their total number of previous purchases, and show the count of each segment

WITH customer_type AS(
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'LOYAL' 
    END AS customer_segment
FROM mytable
)

SELECT customer_segment, COUNT(*) AS "Number of customers"
FROM customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?
SELECT category, item_purchased, purchase_count
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS rank_num
    FROM mytable
    GROUP BY category, item_purchased
) ranked
WHERE rank_num <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, 
COUNT(customer_id) AS repeat_buyers
FROM mytable
WHERE previous_purchases > 5
GROUP BY 1
ORDER BY COUNT(customer_id) DESC;


-- Q10. What is the revenue contribution of each age group
SELECT age_group, 
SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY age_group
ORDER BY total_revenue DESC;